name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: '1.13' 
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run GolangCI-Lint 
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.3
        ./bin/golangci-lint run --enable-all ./...
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --tag rpi-ws281x-builder \
          --load \
          --file Dockerfile .
    - name: Build examples
      run: |    
          docker run --rm -v "$(pwd)"/examples/swiss:/go/src/swiss rpi-ws281x-builder go build -o src/swiss/swiss -v swiss
    - name: Upload examples
      uses: actions/upload-artifact@v1
      with:
        name: swiss
        path: examples/swiss/swiss